name: ColoredTags
author: FlamingGenius
api: 1.12.0
description: Colored nametags
version: 1.0.0
main: FlamingGenius\ColoredTags\ColoredTags
commands:
 sr:
  description: "Set player nametag"
  usage: "sr <tag>"
  default: op
